export const entryFormInitialState = {
  // id: "",
  gameDate: '',
  rank: '',
  outcome: '',
  role: '',
  kills: 0,
  deaths: 0,
  assists: 0,
  champion: '',
  opponentChampion: '',
  partner: '',
  opponentPartner: '',
  csPerMin: 0.0,
  video: '',
  gameId: '',
};
