export const entryFormInitialState = {
  // id: "",
  gameDate: '',
  rank: '',
  outcome: '',
  role: '',
  kills: 0,
  deaths: 0,
  assists: 0,
  champion: '',
  opponentChampion: '',
  jungler: '',
  opponentJungler: '',
  csPerMin: 0.0,
  csAt5Min: 0,
  csAt10Min: 0,
  csAt15Min: 0,
  csAt20Min: 0,
  mistakes: [],
  positives: [],
  lessons: [],
  deathReasons: [],
  roams: [],
  csReasons: [],
  video: '',
};
